### ISSUE TITLE
How do you download via github?

### ISSUE THREAD

**Issue by FancyDucc** [racoonman2/ReTerraForged#60]
Am I just being blind?
I downloaded the zip but I can't find a jar file anywhere and it seems nobody else is having an issue?

**Comment by 1lyDory** [comment]
[reterraforged--1-20-2](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqazF1X2xuTl9WZE5XLVhJVHFHUWZFa0RIMFRnd3xBQ3Jtc0tsMGpabDFBRmlJcWwtMW9udjBOMG5mQnRTdjEtNk0wbFFodnU3alN2LTVzSEd6aUlRVVkxdzFqWmZfNDFzZzMwbzFWZU5YY3pUakxNUWNDVGFJbHhXeE9RUDRfZXpaV0Z5eG01V1o1ZUpWT0NMUGRmTQ&q=https%3A%2F%2Fbit.ly%2Freterraforged--1-20-2&v=5va8fOBKZ1U)

**Comment by jasonrodgers28** [comment]
is there a jar file for forge because i also cant find it anywhere

**Comment by jasonrodgers28** [comment]
1.20.1

**Comment by 1lyDory** [comment]
> [reterraforged--1-20-2](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqazF1X2xuTl9WZE5XLVhJVHFHUWZFa0RIMFRnd3xBQ3Jtc0tsMGpabDFBRmlJcWwtMW9udjBOMG5mQnRTdjEtNk0wbFFodnU3alN2LTVzSEd6aUlRVVkxdzFqWmZfNDFzZzMwbzFWZU5YY3pUakxNUWNDVGFJbHhXeE9RUDRfZXpaV0Z5eG01V1o1ZUpWT0NMUGRmTQ&q=https%3A%2F%2Fbit.ly%2Freterraforged--1-20-2&v=5va8fOBKZ1U)

also suitable for 1.20.1

**Comment by equalizer32** [comment]
Please, don't open issues about installing on GitHub. You won't find any .jar file in the .zip. There is a reason why the mod is currently not downloadable. If you want more info, go ask in the discord. And if you're not already in the Discord then you have  to wait as it's currently closed due to a lot of people joining, who are either new to MC modding and ask stupid questions or pressure the poor dev into doing things he might not even have time for.

**Comment by nellvis** [comment]
they closed the invitations to discord and deleted all jar files from the server

**Comment by equalizer32** [comment]
> they closed the invitations to discord and deleted all jar files from the server

As I have stated, there is a good reason for that. You can try asking someone if they can dm it to you if you want, as that is allowed.

**Comment by Syclusion** [comment]
> > they closed the invitations to discord and deleted all jar files from the server
> 
> As I have stated, there is a good reason for that. You can try asking someone if they can dm it to you if you want, as that is allowed.

Having people join is not a good reason to go scorched earth and allow no jars publically accessible from other means. Your logic is flawed

**Comment by Syclusion** [comment]
> Am I just being blind? I downloaded the zip but I can't find a jar file anywhere and it seems nobody else is having an issue?



> is there a jar file for forge because i also cant find it anywhere

For you guys I am going to tell you the method of building mods without accessible jars, its pretty simple.

First click that green button and download the mod files as a zip. Then in windows open a cmd prompt, you can do that by typing cmd into the search and launching it like that and by setting the directory to wherever you extracted the files. Or by being in the folder and where the directory is at the top, simply type cmd and hit enter.

Then type "gradlew build" without the quotation marks, and the mod will make a jar file for you in the "forge/libs" or "fabric/libs" folders depending on your modloader

**Comment by CookieOfChocolate** [comment]
Can you tell me more specifically, I can't do it the cmd say me: "it is not recognized as an internal or external command,
program or executable batch file"

**Comment by equalizer32** [comment]
> > > they closed the invitations to discord and deleted all jar files from the server
> > 
> > As I have stated, there is a good reason for that. You can try asking someone if they can dm it to you if you want, as that is allowed.
> 
> Having people join is not a good reason to go scorched earth and allow no jars publically accessible from other means. Your logic is flawed


This is a direct quote from the dev: 

"the 0.0.6 update still has a lot of issues and i dont think its stable enough for most people to use yet
id rather most people just wait until 0.0.7 is released"

The reason why the server is closed is because of very large amounts of people joining every day who don't read the faq and then complain about issues in a very early alpha or issues that are completely unrelated to the mod. A lot of people got pissed off, and it was decided to close the server until 0.0.7. A lot of these people joined because they saw reterraforged being used with iris, distant horizons, and shaders. RTF got caught in this crossfire of people joining who never even modded and expect a fully stable release. Xonk, a shader dev, even went crazy in the iris discord because of these exact people, so I think my logic is not flawed.

**Comment by equalizer32** [comment]
And if you really want to compile the mod yourself, then use [this](https://github.com/racoonman2/ReTerraForged/tree/b36860d7d80c60bd59f3f04268af5b47eaa98d01) commit as newer ones may have issues because they're dev test builds

**Comment by Kaletsun** [comment]
> Can you tell me more specifically, I can't do it the cmd say me: "it is not recognized as an internal or external command, program or executable batch file"

i got the same problem, idk what to do
